[package]
name = "vsr-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
blake3 = "1.8.2"
log = "0.4.28"
rand = "0.9.2"
rand_distr = "0.5.1"
tokio = { version = "1.47.1", features = ["full"] }
